### ISSUE TITLE
3.0.x for release apk

### ISSUE THREAD

**Issue by mrpvb-pvbk** [AgoraIO-Community/Agora-Flutter-Quickstart#173]
Currently, it is not possible to use this version of plugin for release build.
Use this command: `flutter run --release` I get the apk file and after installing and running I get this:
```
E/flutter (27900): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Incomplete hierarchy for class AgoraRtcEnginePlugin, unresolved classes [io.flutter.embedding.engine.plugins.FlutterPlugin, io.flutter.plugin.common.MethodChannel.MethodCallHandler, io.flutter.plugin.common.EventChannel.StreamHandler], null)
E/flutter (27900): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
E/flutter (27900): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #2      RtcEngine.createWithAreaCode (package:agora_rtc_engine/src/rtc_engine.dart:88)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #3      AgoraInit._initAgoraRtcEngine (package:streaming_platform/controller/stream_ininialize.dart:20)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #4      AgoraInit.init (package:streaming_platform/controller/stream_ininialize.dart:10)
E/flutter (27900): <asynchronous suspension>
```
Debug works fine.

**Comment by LichKing-2234** [comment]
which version you used.

**Comment by mrpvb-pvbk** [comment]
dev 7, flutter stable 1.20.2

**Comment by mmorales-nubceo** [comment]
@mrpvb-pvbk have you tried this? 
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#android-release-crash
I'm using flutter dev channel latest

**Comment by desarrollomaxijoga10** [comment]
@mrpvb-pvbk have you tried this https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#android-release-crash?

**Comment by LichKing-2234** [comment]
refer to this.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/177#issuecomment-692008309
