### ISSUE TITLE
app crash (build version)

### ISSUE THREAD

**Issue by MortezaHatamiKia** [AgoraIO-Community/Agora-Flutter-Quickstart#19]
my app will be crash after **build** ( in **debug** mode no problem )

### Error
```
msg: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/...-gAgmOrLJRgDIgKsakE2QEw==/base.apk"],nativeLibraryDirectories=[/data/app/...-gAgmOrLJRgDIgKsakE2QEw==/lib/arm64, /data/app/...-gAgmOrLJRgDIgKsakE2QEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
stacktrace: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/...-gAgmOrLJRgDIgKsakE2QEw==/base.apk"],nativeLibraryDirectories=[/data/app/...-gAgmOrLJRgDIgKsakE2QEw==/lib/arm64, /data/app/...-gAgmOrLJRgDIgKsakE2QEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
 at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
 at java.lang.System.loadLibrary(System.java:1669)
 at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:161)
 at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:136)
 at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5932)
 at android.app.ActivityThread.access$1100(ActivityThread.java:202)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6739)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

### My Gradle :
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "..." //my app
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'armeabi-v7a', 'x86' ,'arm64-v8a'
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

### flutter doctor 
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version
    10.0.17763.194], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

• No issues found!

```

### note :  
i use ndk 
```
 ndk {
            abiFilters 'armeabi-v7a', 'x86' ,'arm64-v8a'
       }
```

**Comment by PRWrl** [comment]
`msg: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/...-gAgmOrLJRgDIgKsakE2QEw==/base.apk"],nativeLibraryDirectories=[/data/app/...-gAgmOrLJRgDIgKsakE2QEw==/lib/arm64, /data/app/...-gAgmOrLJRgDIgKsakE2QEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
`

flutter didn't provide 'libflutter.so' in arm64, remove `'arm64-v8a'` from ndk in release mode.

**Comment by MortezaHatamiKia** [comment]
thanks it fixed

**Comment by hamodass** [comment]
I'm Using Agora with flutter and it's work fine in emulator but when i install it in real device after i Enter ch name the app close by itself?

**Comment by LichKing-2234** [comment]
@hamodass any crash log?
