### ISSUE TITLE
Is that worked with flutter Web?

### ISSUE THREAD

**Issue by amarSuthar437** [AgoraIO-Community/Agora-Flutter-Quickstart#214]
Is that working with Flutter web? I'm implementing Video call in flutter web, but i get this exception Missing Plugin.

Error: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
    at Object.throw_ [as throw] (http://localhost:57641/dart_sdk.js:5342:11)
    at MethodChannel._invokeMethod (http://localhost:57641/packages/flutter/src/services/system_channels.dart.lib.js:960:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:57641/dart_sdk.js:39157:33
    at _RootZone.runUnary (http://localhost:57641/dart_sdk.js:39014:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:57641/dart_sdk.js:34000:29)
    at handleValueCallback (http://localhost:57641/dart_sdk.js:34560:49)
    at Function._propagateToListeners (http://localhost:57641/dart_sdk.js:34598:17)
    at _Future.new.[_completeWithValue] (http://localhost:57641/dart_sdk.js:34440:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57641/dart_sdk.js:34463:35)
    at Object._microtaskLoop (http://localhost:57641/dart_sdk.js:39301:13)
    at _startMicrotaskLoop (http://localhost:57641/dart_sdk.js:39307:13)
    at http://localhost:57641/dart_sdk.js:34814:9

**Comment by LichKing-2234** [comment]
it did not support the web yet.

**Comment by LichKing-2234** [comment]
you can follow https://github.com/AgoraIO/Agora-Flutter-SDK/issues/63
