### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by Akifcan** [AgoraIO-Community/Agora-Flutter-Quickstart#233]
Hello, before 3 month ago i used agora sdk with flutter and it was working successfully. Now i tried to implement again agora sdk to my flutter app. I created a new project and used appId and token in my app but it still gives me invalid token error. 

Also in console i have this errors
`E/libc    ( 8822): Access denied finding property "net.dns1"`
```
W/GENP.0  ( 8822): type=1400 audit(0.0:4953): avc: denied { read } for name="temp" dev="sysfs" ino=13781 scontext=u:r:untrusted_app:s0:c140,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/System.err( 8822): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err( 8822): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err( 8822): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err( 8822): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err( 8822): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err( 8822): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 8822): 	at libcore.io.Linux.open(Native Method)
W/System.err( 8822): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 8822): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err( 8822): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 8822): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
W/System.err( 8822): 	at libcore.io.IoBridge.open(IoBridge.java:482)
```

Android manifest
```
 <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
pubspec.yaml
```
agora_rtc_engine: ^4.0.2
  permission_handler: ^8.1.1
```

**Comment by LichKing-2234** [comment]
you can ignore this log, pls listen the error event or fetch the SDK log to get more info.

**Comment by Akifcan** [comment]
hello again this is message from error event `I/flutter ( 8377): errorErrorCode.InvalidAppId`

**Comment by LichKing-2234** [comment]
have you set the toekn?

**Comment by TheStarkster** [comment]
> you can ignore this log, pls listen the error event or fetch the SDK log to get more info.

even if i ignore that i am not able to listen from audience role

**Comment by LichKing-2234** [comment]
@TheStarkster Sorry, I don't understand. Could you pls explain your issue?

**Comment by TheStarkster** [comment]
@LichKing-2234 Nevermind its resolved, thanks!

**Comment by LichKing-2234** [comment]
@TheStarkster Cloud you pls share the cause, it may help other developers, thanks!

**Comment by TheStarkster** [comment]
for the error `type=1400 audit(0.0:4953): avc: denied { read } for name="temp" dev="sysfs" ino=13781 .....`
i just make sure that i am asking for permission (mic permission) using permission handler package, because without that, when i explicitly provide mic permission (from device's settings) to the app it works

and for __token error__ there's possibility that @Akifcan may've not enabled APP certificate for the new project

**Comment by Akifcan** [comment]
i'm so sorry for delay but yes i enabled certificate and works fine :)

**Comment by Nasirdev74** [comment]
> have you set the token?

hi, I'm just trying to implement the demo. but I don't get it. how can I get my token??
what is the token used for?? 
I can't find anything about the new 'token' thing .. 
Please help me with some doc or something. 
thank you.

**Comment by TheStarkster** [comment]
@Nasirdev74 you're supposed to pass the token in RtcEngine's `joinChannel` method. Check out [this code snippet](https://docs.agora.io/en/Voice/start_call_audio_flutter?platform=Flutter#4-define-app-states) and look at the last line of initPlatformState method

**Comment by maxxfrazer** [comment]
Closing due to inactivity
