### ISSUE TITLE
Error: MissingPluginException

### ISSUE THREAD

**Issue by nisaji** [AgoraIO-Community/Agora-Flutter-Quickstart#234]
When I ```flutter run``` (or ```flutter run -d chrome``` )

```
Error: MissingPluginException(No implementation found for method
requestPermissions on channel flutter.baseflow.com/permissions/methods)
    at Object.throw_ [as throw]
    (http://localhost:51947/dart_sdk.js:5041:11)
    at MethodChannel._invokeMethod
    (http://localhost:51947/packages/flutter/src/services/system_channel
    s.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:51947/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:51947/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue
    (http://localhost:51947/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:51947/dart_sdk.js:33057:49)
    at Function._propagateToListeners
    (http://localhost:51947/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue]
    (http://localhost:51947/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback
    (http://localhost:51947/dart_sdk.js:32964:35)
    at Object._microtaskLoop
    (http://localhost:51947/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:51947/dart_sdk.js:37532:13)
    at http://localhost:51947/dart_sdk.js:33303:9
```

Is there any solutions in this problem ?

**Comment by LichKing-2234** [comment]
for flutter web? pls refer to https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev/flutter2/example.

**Comment by nisaji** [comment]
Thank you.

In `lib/config/agora.comfig`, I can see
```
/// Get your own App ID at https://dashboard.agora.io/
const appId = YOUR_APP_ID;

/// Please refer to https://docs.agora.io/en/Agora%20Platform/token
const token = YOUR_TOEKN;

/// Your channel ID
const channelId = YOUR_CHANNEL_ID;

/// Your int user ID
const uid = YOUR_UID;

/// Your string user ID
const stringUid = YOUR_STRING_UID;
```

where I get `channelId`, `uid` and `stringUid`?

**Comment by LichKing-2234** [comment]
you can special by yourself.

**Comment by nisaji** [comment]
Thanks.

I run presented by you on web, I cought same error as below.
```
Error: MissingPluginException(No implementation found for method
create on channel agora_rtc_engine)
    at Object.throw_ [as throw]
    (http://localhost:56023/dart_sdk.js:5041:11)
    at MethodChannel._invokeMethod
    (http://localhost:56023/packages/flutter/src/services/system_chan
    nels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:56023/dart_sdk.js:37403:33
    at _RootZone.runUnary
    (http://localhost:56023/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue
    (http://localhost:56023/dart_sdk.js:32530:29)
    at handleValueCallback
    (http://localhost:56023/dart_sdk.js:33057:49)
    at Function._propagateToListeners
    (http://localhost:56023/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue]
    (http://localhost:56023/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback
    (http://localhost:56023/dart_sdk.js:32964:35)
    at Object._microtaskLoop
    (http://localhost:56023/dart_sdk.js:37526:13)
    at _startMicrotaskLoop
    (http://localhost:56023/dart_sdk.js:37532:13)
    at http://localhost:56023/dart_sdk.js:33303:9
```

But, when I run iOS emulator, It may works correctly.
So I can develop with emulator but I want to develop on web(chrome).
Do you have any solution ?

**Comment by LichKing-2234** [comment]
pls refer to https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev/flutter2/example.
