### ISSUE TITLE
Flutter initialization failed.

### ISSUE THREAD

**Issue by MasoomRaza752** [AgoraIO-Community/Agora-Flutter-Quickstart#245]
I use agora rtc engin 4.2.0 and it show me the error when i open my app after putting dependency 'agora_rtc_engine: ^4.0.7' and my app is crashing in debug mode and show the error

√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/FlutterLoader(17183): Flutter initialization failed.
E/FlutterLoader(17183): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.video_call_test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.video_call_test-1/lib/arm, /data/app/com.example.video_c

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

• No issues found!

**Comment by LichKing-2234** [comment]
I can't get any error about our SDK, pls double-check your project.

**Comment by LichKing-2234** [comment]
BTW, you can refer to https://github.com/AgoraIO/Agora-Flutter-SDK/tree/master/example

**Comment by MasoomRaza752** [comment]
i use this code also in saprate but error is still there.

**Comment by MasoomRaza752** [comment]
when i use this line in my code :
      implementation 'io.agora.rtc:full-sdk:3.6.1.1'

it shows me this type off error plese guide me i'm stuck on it this is last stage of my project 

   Duplicate class com.coloros.ocs.base.task.k found in modules jetified-full-sdk-3.6.1-runtime (io.agora.rtc:full-sdk:3.6.1.1) and jetified-native-full-sdk-3.5.2-runtime (com.github.agorabuilder:native-full-sdk:3.5.2)
     Duplicate class com.coloros.ocs.base.task.l found in modules jetified-full-sdk-3.6.1-runtime (io.agora.rtc:full-sdk:3.6.1.1) and jetified-native-full-sdk-3.5.2-runtime (com.github.agorabuilder:native-full-sdk:3.5.2)
     Duplicate class com.coloros.ocs.base.task.m found in modules jetified-full-sdk-3.6.1-runtime (io.agora.rtc:full-sdk:3.6.1.1) and jetified-native-full-sdk-3.5.2-runtime (com.github.agorabuilder:native-full-sdk:3.5.2)
     Duplicate class com.coloros.ocs.base.task.n found in modules jetified-full-sdk-3.6.1-runtime (io.agora.rtc:full-sdk:3.6.1.1) and jetified-native-full-sdk-3.5.2-runtime (com.github.agorabuilder:native-full-sdk:3.5.2)
     Duplicate class com.coloros.ocs.base.task.o found in modules jetified-full-sdk-3.6.1-runtime (io.agora.rtc:full-sdk:3.6.1.1) and jetified-native-full-sdk-3.5.2-runtime (com.github.agorabuilder:native-full-sdk:3.5.2)

**Comment by LichKing-2234** [comment]
you can try to run our example first.

**Comment by MasoomRaza752** [comment]
i downlaod the code from agora quick start and try to run it just putting my app id and token and it shows the following error also

 Built build\app\outputs\flutter-apk\app-debug.apk.
E/FlutterLoader(15242): Flutter initialization failed.
E/FlutterLoader(15242): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.agoraflutterquickstart-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.agoraflutterquickstart-1/lib/arm, /data/app/com.example.agoraflutterquickstart-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(15242): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E/FlutterLoader(15242): 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E/FlutterLoader(15242): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:223)
E/FlutterLoader(15242): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:326)
E/FlutterLoader(15242): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:206)
E/FlutterLoader(15242): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:256)
E/FlutterLoader(15242): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:166)
E/FlutterLoader(15242): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/FlutterLoader(15242): 	at android.app.Activity.performCreate(Activity.java:6739)
E/FlutterLoader(15242): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

**Comment by MasoomRaza752** [comment]
Flutter initialization failed.
couldn't find "libflutter.so"

**Comment by MasoomRaza752** [comment]
what are the firewall requirments for this and how edit them?

**Comment by MasoomRaza752** [comment]
minSdkVersion 25
 targetSdkVersion 29
compileSdkVersion 31

please chek these value are right or wrong beacuse when i give minSdk to 31 my emulator shows minSdk is 25 and did not show any other error please guide about this
