### ISSUE TITLE
flutter build apk 后安装到设备无法打开

### ISSUE THREAD

**Issue by yangxiaoge** [AgoraIO-Community/Agora-Flutter-Quickstart#3]

**Comment by yangxiaoge** [comment]
2019-03-12 14:08:57.859 5376-5376/com.example.agoraflutterquickstart E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.agoraflutterquickstart, PID: 5376
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.agoraflutterquickstart-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.agoraflutterquickstart-2/lib/arm64, /data/app/com.example.agoraflutterquickstart-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1530)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:156)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:133)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by plutoless** [comment]
couldn't find "libflutter.so"
感觉flutter环境配置有问题，先跑一下flutter doctor看下结果

**Comment by plutoless** [comment]
👍
