### ISSUE TITLE
打包签名apk后，安装直接退出，无法打开

### ISSUE THREAD

**Issue by ngu2008** [AgoraIO-Community/Agora-Flutter-Quickstart#7]
打包签名apk后，安装直接退出，无法打开

**Comment by plutoless** [comment]
给一下错误日志？

**Comment by ngu2008** [comment]
我是直接git clone 下来的这个项目，声网新建了个项目，填写setting.dart中替换appid，在真机上debug版本运行是ok的，签名打包的release版本打不开，安装打开直接退出

**Comment by plutoless** [comment]
我这边试了下好像没问题，这种情况一般是crash了，你这边提取一下错误日志我们可以看下详细原因

**Comment by guohai** [comment]
这个可能跟 abi 有关?

**Comment by maxucheng0** [comment]
logcat 拦截报错：
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.agoraflutterquickstart-Xenj8uEirxs8_F1-pTL6Wg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.agoraflutterquickstart-Xenj8uEirxs8_F1-pTL6Wg==/lib/arm64, /data/app/com.example.agoraflutterquickstart-Xenj8uEirxs8_F1-pTL6Wg==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:161)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:136)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1165)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
        at android.app.ActivityThread.access$1300(ActivityThread.java:209)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1790)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6954)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by plutoless** [comment]
最新的flutter engine应该已经解决了，这边可以升级flutter试一下吗？

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Flutter-SDK/issues/21

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
